// Dark Mode
export const GET_THEME = 'GET_THEME';
export const UPDATE_THEME = 'UPDATE_THEME';
export const SET_DARK_MODE = 'SET_DARK_MODE';
export const SET_LIGHT_MODE = 'SET_LIGHT_MODE';

// Others
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const GET_TODAY_QUESTIONS = 'GET_TODAY_QUESTIONS';
export const GET_SOLVED_QUESTIONS = 'GET_SOLVED_QUESTIONS';
export const SET_QUESTION = 'SET_QUESTION';
export const SET_QUESTION_SUCCESS = 'SET_QUESTION_SUCCESS';